pub mod types;
pub use types::*;

/// Re-export serde_json::Value for convenience.
pub use serde_json::Value;

/// Hidden re-exports used by the `export_*!` macros.
/// Not part of the public API — do not depend on these directly.
/// Add new re-exports here as future macros require them.
#[doc(hidden)]
pub mod __macro_support {
    pub use serde_json;
    pub use std::sync::OnceLock;
}

/// Trait for WASM guest tool implementations.
///
/// All methods are synchronous — WASM guests are single-threaded.
pub trait Tool {
    /// Returns the tool's name.
    fn name(&self) -> &str;

    /// Returns the tool specification (name, parameters, description).
    fn get_spec(&self) -> ToolSpec;

    /// Executes the tool with the given JSON input.
    fn execute(&self, input: Value) -> Result<ToolResult, String>;
}

/// Exports a [`Tool`] implementation as WASM guest entry points.
///
/// Creates a singleton instance via `OnceLock` and generates `#[no_mangle] pub extern "C"`
/// functions that the host can call to discover and invoke the tool.
///
/// # Usage
///
/// ```ignore
/// #[derive(Default)]
/// struct MyTool;
///
/// impl Tool for MyTool { /* ... */ }
///
/// export_tool!(MyTool);
/// ```
///
/// # Generated items
///
/// - `get_tool() -> &'static $tool_type` — returns the singleton instance
/// - `__amplifier_tool_get_spec_len() -> u32` — byte length of the JSON-serialized [`ToolSpec`]
/// - `__amplifier_tool_get_spec(ptr: *mut u8)` — writes serialized spec into caller-provided buffer
///
/// **Note:** This is a simplified scaffold. Real Component Model exports use `wit-bindgen`'s
/// `generate!` macro. The macro internals will be adjusted when compiling the first fixture,
/// but the module-author interface (`impl Tool` + `export_tool!`) will not change.
/// Exports a [`Tool`] implementation as WASM guest entry points.
///
/// On **native targets** (testing), generates `#[no_mangle] pub extern "C"` functions
/// for spec introspection (`__amplifier_tool_get_spec_len`, `__amplifier_tool_get_spec`).
///
/// On **wasm32 targets** (Component Model), generates `wit-bindgen` Guest trait
/// implementation and component exports. Requires the calling crate to declare
/// `mod bindings;` (generated by `cargo component`) and depend on `wit-bindgen-rt`.
///
/// # Usage
///
/// ```ignore
/// #[derive(Default)]
/// struct MyTool;
///
/// impl Tool for MyTool { /* ... */ }
///
/// export_tool!(MyTool);
/// ```
///
/// # Generated items
///
/// - `get_tool() -> &'static $tool_type` — returns the singleton instance
/// - (native) `__amplifier_tool_get_spec_len() -> u32` — byte length of the JSON-serialized [`ToolSpec`]
/// - (native) `__amplifier_tool_get_spec(ptr: *mut u8)` — writes serialized spec into caller-provided buffer
/// - (wasm32) `impl bindings::exports::amplifier::modules::tool::Guest` — Component Model bridge
/// - (wasm32) `bindings::export!` invocation — wires up component exports
#[macro_export]
macro_rules! export_tool {
    ($tool_type:ident) => {
        // Tool singleton, lazily initialised via Default.
        static __AMPLIFIER_TOOL: $crate::__macro_support::OnceLock<$tool_type> =
            $crate::__macro_support::OnceLock::new();

        /// Returns a reference to the tool singleton.
        fn get_tool() -> &'static $tool_type {
            __AMPLIFIER_TOOL
                .get_or_init(|| <$tool_type as ::std::default::Default>::default())
        }

        // ----- Native target: C-ABI exports for testing -----

        // Lazily cached JSON representation of the ToolSpec.
        #[cfg(not(target_arch = "wasm32"))]
        static __AMPLIFIER_SPEC_CACHE: $crate::__macro_support::OnceLock<::std::vec::Vec<u8>> =
            $crate::__macro_support::OnceLock::new();

        #[cfg(not(target_arch = "wasm32"))]
        fn __amplifier_cached_spec() -> &'static [u8] {
            __AMPLIFIER_SPEC_CACHE.get_or_init(|| {
                let spec = <$tool_type as $crate::Tool>::get_spec(get_tool());
                $crate::__macro_support::serde_json::to_vec(&spec)
                    .expect("ToolSpec serialization must not fail")
            })
        }

        /// Returns the byte length of the JSON-serialized [`ToolSpec`].
        #[cfg(not(target_arch = "wasm32"))]
        #[no_mangle]
        pub extern "C" fn __amplifier_tool_get_spec_len() -> u32 {
            __amplifier_cached_spec().len().try_into()
                .expect("serialized ToolSpec must fit in u32 (WASM linear memory is ≤ 4 GiB)")
        }

        /// Copies the JSON-serialized [`ToolSpec`] into the buffer at `ptr`.
        ///
        /// # Safety
        ///
        /// The caller must provide a non-null buffer of at least
        /// `__amplifier_tool_get_spec_len()` bytes.
        #[cfg(not(target_arch = "wasm32"))]
        #[no_mangle]
        pub unsafe extern "C" fn __amplifier_tool_get_spec(ptr: *mut u8) {
            if ptr.is_null() {
                return;
            }
            let json = __amplifier_cached_spec();
            ::std::ptr::copy_nonoverlapping(json.as_ptr(), ptr, json.len());
        }

        // ----- WASM target: Component Model exports -----

        #[cfg(target_arch = "wasm32")]
        impl bindings::exports::amplifier::modules::tool::Guest for $tool_type {
            fn get_spec() -> ::std::vec::Vec<u8> {
                let spec = <$tool_type as $crate::Tool>::get_spec(get_tool());
                $crate::__macro_support::serde_json::to_vec(&spec)
                    .expect("ToolSpec serialization must not fail")
            }

            fn execute(input: ::std::vec::Vec<u8>) -> ::core::result::Result<::std::vec::Vec<u8>, ::std::string::String> {
                let input_val: $crate::Value =
                    $crate::__macro_support::serde_json::from_slice(&input)
                        .map_err(|e| e.to_string())?;
                let result = <$tool_type as $crate::Tool>::execute(get_tool(), input_val)?;
                $crate::__macro_support::serde_json::to_vec(&result)
                    .map_err(|e| e.to_string())
            }
        }

        #[cfg(target_arch = "wasm32")]
        bindings::export!($tool_type with_types_in bindings);
    };
}

// ---------------------------------------------------------------------------
// HookHandler trait
// ---------------------------------------------------------------------------

/// Trait for WASM guest hook handler implementations.
///
/// All methods are synchronous — WASM guests are single-threaded.
pub trait HookHandler {
    /// Handles a lifecycle event, returning an action the host should take.
    fn handle(&self, event: &str, data: Value) -> Result<HookResult, String>;
}

/// Exports a [`HookHandler`] implementation as WASM guest entry points.
///
/// Creates a singleton instance via `OnceLock` and generates accessor functions
/// that the host can call to dispatch hook events.
///
/// # Usage
///
/// ```ignore
/// #[derive(Default)]
/// struct MyHook;
///
/// impl HookHandler for MyHook { /* ... */ }
///
/// export_hook!(MyHook);
/// ```
#[macro_export]
macro_rules! export_hook {
    ($hook_type:ident) => {
        static __AMPLIFIER_HOOK: $crate::__macro_support::OnceLock<$hook_type> =
            $crate::__macro_support::OnceLock::new();

        /// Returns a reference to the hook handler singleton.
        fn get_hook() -> &'static $hook_type {
            __AMPLIFIER_HOOK
                .get_or_init(|| <$hook_type as ::std::default::Default>::default())
        }

        // ----- WASM target: Component Model exports -----

        #[cfg(target_arch = "wasm32")]
        impl bindings::exports::amplifier::modules::hook_handler::Guest for $hook_type {
            fn handle(event: ::std::vec::Vec<u8>) -> ::core::result::Result<::std::vec::Vec<u8>, ::std::string::String> {
                // Deserialize the event bytes as a JSON object with "event" and "data" fields.
                let envelope: $crate::Value =
                    $crate::__macro_support::serde_json::from_slice(&event)
                        .map_err(|e| e.to_string())?;
                let event_str = envelope.get("event")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                let data = envelope.get("data")
                    .cloned()
                    .unwrap_or($crate::Value::Null);
                let result = <$hook_type as $crate::HookHandler>::handle(get_hook(), event_str, data)?;
                $crate::__macro_support::serde_json::to_vec(&result)
                    .map_err(|e| e.to_string())
            }
        }

        #[cfg(target_arch = "wasm32")]
        bindings::export!($hook_type with_types_in bindings);
    };
}

// ---------------------------------------------------------------------------
// ContextManager trait
// ---------------------------------------------------------------------------

/// Trait for WASM guest context manager implementations.
///
/// All methods are synchronous — WASM guests are single-threaded.
pub trait ContextManager {
    /// Adds a message to the context window.
    fn add_message(&self, message: Value) -> Result<(), String>;

    /// Returns all messages in the context window.
    fn get_messages(&self) -> Result<Vec<Value>, String>;

    /// Returns messages relevant to the given request.
    fn get_messages_for_request(&self, request: Value) -> Result<Vec<Value>, String>;

    /// Replaces the context window with the given messages.
    fn set_messages(&self, messages: Vec<Value>) -> Result<(), String>;

    /// Clears all messages from the context window.
    fn clear(&self) -> Result<(), String>;
}

/// Exports a [`ContextManager`] implementation as WASM guest entry points.
///
/// Creates a singleton instance via `OnceLock` and generates accessor functions
/// that the host can call to manage context.
///
/// # Usage
///
/// ```ignore
/// #[derive(Default)]
/// struct MyContext;
///
/// impl ContextManager for MyContext { /* ... */ }
///
/// export_context!(MyContext);
/// ```
#[macro_export]
macro_rules! export_context {
    ($ctx_type:ident) => {
        static __AMPLIFIER_CONTEXT: $crate::__macro_support::OnceLock<$ctx_type> =
            $crate::__macro_support::OnceLock::new();

        /// Returns a reference to the context manager singleton.
        fn get_context() -> &'static $ctx_type {
            __AMPLIFIER_CONTEXT
                .get_or_init(|| <$ctx_type as ::std::default::Default>::default())
        }

        // ----- WASM target: Component Model exports -----

        #[cfg(target_arch = "wasm32")]
        impl bindings::exports::amplifier::modules::context_manager::Guest for $ctx_type {
            fn add_message(message: ::std::vec::Vec<u8>) -> ::core::result::Result<(), ::std::string::String> {
                let msg: $crate::Value =
                    $crate::__macro_support::serde_json::from_slice(&message)
                        .map_err(|e| e.to_string())?;
                <$ctx_type as $crate::ContextManager>::add_message(get_context(), msg)
            }

            fn get_messages() -> ::core::result::Result<::std::vec::Vec<u8>, ::std::string::String> {
                let messages = <$ctx_type as $crate::ContextManager>::get_messages(get_context())?;
                $crate::__macro_support::serde_json::to_vec(&messages)
                    .map_err(|e| e.to_string())
            }

            fn get_messages_for_request(params: ::std::vec::Vec<u8>) -> ::core::result::Result<::std::vec::Vec<u8>, ::std::string::String> {
                let request: $crate::Value =
                    $crate::__macro_support::serde_json::from_slice(&params)
                        .map_err(|e| e.to_string())?;
                let messages = <$ctx_type as $crate::ContextManager>::get_messages_for_request(get_context(), request)?;
                $crate::__macro_support::serde_json::to_vec(&messages)
                    .map_err(|e| e.to_string())
            }

            fn set_messages(messages: ::std::vec::Vec<u8>) -> ::core::result::Result<(), ::std::string::String> {
                let msgs: ::std::vec::Vec<$crate::Value> =
                    $crate::__macro_support::serde_json::from_slice(&messages)
                        .map_err(|e| e.to_string())?;
                <$ctx_type as $crate::ContextManager>::set_messages(get_context(), msgs)
            }

            fn clear() -> ::core::result::Result<(), ::std::string::String> {
                <$ctx_type as $crate::ContextManager>::clear(get_context())
            }
        }

        #[cfg(target_arch = "wasm32")]
        bindings::export!($ctx_type with_types_in bindings);
    };
}

// ---------------------------------------------------------------------------
// ApprovalProvider trait
// ---------------------------------------------------------------------------

/// Trait for WASM guest approval provider implementations.
///
/// All methods are synchronous — WASM guests are single-threaded.
pub trait ApprovalProvider {
    /// Requests human-in-the-loop approval for a given action.
    fn request_approval(&self, request: ApprovalRequest) -> Result<ApprovalResponse, String>;
}

/// Exports an [`ApprovalProvider`] implementation as WASM guest entry points.
///
/// Creates a singleton instance via `OnceLock` and generates accessor functions
/// that the host can call to request approvals.
///
/// # Usage
///
/// ```ignore
/// #[derive(Default)]
/// struct MyApproval;
///
/// impl ApprovalProvider for MyApproval { /* ... */ }
///
/// export_approval!(MyApproval);
/// ```
#[macro_export]
macro_rules! export_approval {
    ($approval_type:ident) => {
        static __AMPLIFIER_APPROVAL: $crate::__macro_support::OnceLock<$approval_type> =
            $crate::__macro_support::OnceLock::new();

        /// Returns a reference to the approval provider singleton.
        fn get_approval() -> &'static $approval_type {
            __AMPLIFIER_APPROVAL
                .get_or_init(|| <$approval_type as ::std::default::Default>::default())
        }

        // ----- WASM target: Component Model exports -----

        #[cfg(target_arch = "wasm32")]
        impl bindings::exports::amplifier::modules::approval_provider::Guest for $approval_type {
            fn request_approval(request: ::std::vec::Vec<u8>) -> ::core::result::Result<::std::vec::Vec<u8>, ::std::string::String> {
                let req: $crate::ApprovalRequest =
                    $crate::__macro_support::serde_json::from_slice(&request)
                        .map_err(|e| e.to_string())?;
                let result = <$approval_type as $crate::ApprovalProvider>::request_approval(get_approval(), req)?;
                $crate::__macro_support::serde_json::to_vec(&result)
                    .map_err(|e| e.to_string())
            }
        }

        #[cfg(target_arch = "wasm32")]
        bindings::export!($approval_type with_types_in bindings);
    };
}

// ---------------------------------------------------------------------------
// Provider trait
// ---------------------------------------------------------------------------

/// Trait for WASM guest LLM provider implementations.
///
/// All methods are synchronous — WASM guests are single-threaded.
pub trait Provider {
    /// Returns the provider's name.
    fn name(&self) -> &str;

    /// Returns metadata about this provider.
    fn get_info(&self) -> ProviderInfo;

    /// Lists the models available from this provider.
    fn list_models(&self) -> Result<Vec<ModelInfo>, String>;

    /// Sends a chat completion request and returns the response.
    fn complete(&self, request: Value) -> Result<ChatResponse, String>;

    /// Extracts tool calls from a chat response.
    fn parse_tool_calls(&self, response: &ChatResponse) -> Vec<Value>;
}

/// Exports a [`Provider`] implementation as WASM guest entry points.
///
/// Creates a singleton instance via `OnceLock` and generates accessor functions
/// that the host can call to discover and invoke the provider.
///
/// # Usage
///
/// ```ignore
/// #[derive(Default)]
/// struct MyProvider;
///
/// impl Provider for MyProvider { /* ... */ }
///
/// export_provider!(MyProvider);
/// ```
#[macro_export]
macro_rules! export_provider {
    ($provider_type:ident) => {
        static __AMPLIFIER_PROVIDER: $crate::__macro_support::OnceLock<$provider_type> =
            $crate::__macro_support::OnceLock::new();

        /// Returns a reference to the provider singleton.
        fn get_provider() -> &'static $provider_type {
            __AMPLIFIER_PROVIDER
                .get_or_init(|| <$provider_type as ::std::default::Default>::default())
        }

        // ----- WASM target: Component Model exports -----

        #[cfg(target_arch = "wasm32")]
        impl bindings::exports::amplifier::modules::provider::Guest for $provider_type {
            fn get_info() -> ::std::vec::Vec<u8> {
                let info = <$provider_type as $crate::Provider>::get_info(get_provider());
                $crate::__macro_support::serde_json::to_vec(&info)
                    .expect("ProviderInfo serialization must not fail")
            }

            fn list_models() -> ::core::result::Result<::std::vec::Vec<u8>, ::std::string::String> {
                let models = <$provider_type as $crate::Provider>::list_models(get_provider())?;
                $crate::__macro_support::serde_json::to_vec(&models)
                    .map_err(|e| e.to_string())
            }

            fn complete(
                request: ::std::vec::Vec<u8>,
            ) -> ::core::result::Result<::std::vec::Vec<u8>, ::std::string::String> {
                let req: $crate::Value =
                    $crate::__macro_support::serde_json::from_slice(&request)
                        .map_err(|e| e.to_string())?;
                let response = <$provider_type as $crate::Provider>::complete(get_provider(), req)?;
                $crate::__macro_support::serde_json::to_vec(&response)
                    .map_err(|e| e.to_string())
            }

            fn parse_tool_calls(
                response: ::std::vec::Vec<u8>,
            ) -> ::core::result::Result<::std::vec::Vec<u8>, ::std::string::String> {
                let resp: $crate::ChatResponse =
                    $crate::__macro_support::serde_json::from_slice(&response)
                        .map_err(|e| e.to_string())?;
                let calls =
                    <$provider_type as $crate::Provider>::parse_tool_calls(get_provider(), &resp);
                $crate::__macro_support::serde_json::to_vec(&calls)
                    .map_err(|e| e.to_string())
            }
        }

        #[cfg(target_arch = "wasm32")]
        bindings::export!($provider_type with_types_in bindings);
    };
}

// ---------------------------------------------------------------------------
// Orchestrator trait
// ---------------------------------------------------------------------------

/// Trait for WASM guest orchestrator implementations.
///
/// All methods are synchronous — WASM guests are single-threaded.
pub trait Orchestrator {
    /// Executes an orchestration loop for the given prompt.
    fn execute(&self, prompt: String) -> Result<String, String>;
}

/// Exports an [`Orchestrator`] implementation as WASM guest entry points.
///
/// Creates a singleton instance via `OnceLock` and generates accessor functions
/// that the host can call to run orchestration.
///
/// # Usage
///
/// ```ignore
/// #[derive(Default)]
/// struct MyOrchestrator;
///
/// impl Orchestrator for MyOrchestrator { /* ... */ }
///
/// export_orchestrator!(MyOrchestrator);
/// ```
#[macro_export]
macro_rules! export_orchestrator {
    ($orch_type:ty) => {
        static __AMPLIFIER_ORCHESTRATOR: $crate::__macro_support::OnceLock<$orch_type> =
            $crate::__macro_support::OnceLock::new();

        /// Returns a reference to the orchestrator singleton.
        fn get_orchestrator() -> &'static $orch_type {
            __AMPLIFIER_ORCHESTRATOR
                .get_or_init(|| <$orch_type as ::std::default::Default>::default())
        }
    };
}

// ---------------------------------------------------------------------------
// Kernel-service import wrappers
// ---------------------------------------------------------------------------

/// Placeholder wrappers for kernel-service WIT imports.
///
/// These functions will be wired to real WIT imports when the Component Model
/// bindings are generated. Until then, every function returns an `Err` with a
/// descriptive placeholder message.
pub mod kernel {
    use serde_json::Value;
    use crate::types::{HookResult, ToolResult};

    /// Executes a tool by name through the kernel.
    pub fn execute_tool(_name: &str, _input: &Value) -> Result<ToolResult, String> {
        Err("kernel::execute_tool: not yet wired to WIT imports".to_string())
    }

    /// Sends a completion request to a named provider through the kernel.
    pub fn complete_with_provider(_name: &str, _request: &Value) -> Result<Value, String> {
        Err("kernel::complete_with_provider: not yet wired to WIT imports".to_string())
    }

    /// Emits a lifecycle hook event through the kernel.
    pub fn emit_hook(_event: &str, _data: &Value) -> Result<HookResult, String> {
        Err("kernel::emit_hook: not yet wired to WIT imports".to_string())
    }

    /// Retrieves all messages from the kernel's context.
    pub fn get_messages() -> Result<Vec<Value>, String> {
        Err("kernel::get_messages: not yet wired to WIT imports".to_string())
    }

    /// Adds a message to the kernel's context.
    pub fn add_message(_message: &Value) -> Result<(), String> {
        Err("kernel::add_message: not yet wired to WIT imports".to_string())
    }

    /// Retrieves a capability value by name from the kernel.
    pub fn get_capability(_name: &str) -> Result<Value, String> {
        Err("kernel::get_capability: not yet wired to WIT imports".to_string())
    }

    /// Registers a capability value by name with the kernel.
    pub fn register_capability(_name: &str, _value: &Value) -> Result<(), String> {
        Err("kernel::register_capability: not yet wired to WIT imports".to_string())
    }
}

#[cfg(test)]
mod tool_tests {
    use super::*;
    use serde_json::json;
    use std::collections::HashMap;

    // A minimal test tool for verifying the trait contract.
    #[derive(Default)]
    struct EchoTool;

    impl Tool for EchoTool {
        fn name(&self) -> &str {
            "echo"
        }

        fn get_spec(&self) -> ToolSpec {
            let mut params = HashMap::new();
            params.insert("message".to_string(), json!({"type": "string"}));
            ToolSpec {
                name: "echo".to_string(),
                parameters: params,
                description: Some("Echoes the input".to_string()),
            }
        }

        fn execute(&self, input: Value) -> Result<ToolResult, String> {
            Ok(ToolResult {
                success: true,
                output: Some(input),
                error: None,
            })
        }
    }

    #[test]
    fn test_tool_trait_name() {
        let tool = EchoTool;
        assert_eq!(tool.name(), "echo");
    }

    #[test]
    fn test_tool_trait_get_spec() {
        let tool = EchoTool;
        let spec = tool.get_spec();
        assert_eq!(spec.name, "echo");
        assert!(spec.parameters.contains_key("message"));
        assert_eq!(spec.description, Some("Echoes the input".to_string()));
    }

    #[test]
    fn test_tool_trait_execute_success() {
        let tool = EchoTool;
        let input = json!({"message": "hello"});
        let result = tool.execute(input.clone());
        assert!(result.is_ok());
        let result = result.unwrap();
        assert!(result.success);
        assert_eq!(result.output, Some(input));
    }

    #[test]
    fn test_tool_trait_get_spec_empty_parameters() {
        let spec = ToolSpec {
            name: "noop".to_string(),
            parameters: HashMap::new(),
            description: None,
        };
        let json_str = serde_json::to_string(&spec).unwrap();
        let deserialized: ToolSpec = serde_json::from_str(&json_str).unwrap();
        assert!(deserialized.parameters.is_empty());
        // Verify the parameters field serializes as an empty object.
        let raw: serde_json::Value = serde_json::from_str(&json_str).unwrap();
        assert_eq!(raw["parameters"], json!({}));
    }

    #[test]
    fn test_tool_trait_execute_error() {
        #[derive(Default)]
        struct FailTool;

        impl Tool for FailTool {
            fn name(&self) -> &str {
                "fail"
            }
            fn get_spec(&self) -> ToolSpec {
                ToolSpec {
                    name: "fail".to_string(),
                    parameters: HashMap::new(),
                    description: None,
                }
            }
            fn execute(&self, _input: Value) -> Result<ToolResult, String> {
                Err("something went wrong".to_string())
            }
        }

        let tool = FailTool;
        let result = tool.execute(json!({}));
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), "something went wrong");
    }
}

#[cfg(test)]
mod macro_tests {
    use super::*;
    use serde_json::json;
    use std::collections::HashMap;

    #[derive(Default)]
    struct MacroTestTool;

    impl Tool for MacroTestTool {
        fn name(&self) -> &str {
            "macro_test"
        }
        fn get_spec(&self) -> ToolSpec {
            let mut params = HashMap::new();
            params.insert("x".to_string(), json!({"type": "integer"}));
            ToolSpec {
                name: "macro_test".to_string(),
                parameters: params,
                description: Some("A test tool for macro validation".to_string()),
            }
        }
        fn execute(&self, input: Value) -> Result<ToolResult, String> {
            Ok(ToolResult {
                success: true,
                output: Some(input),
                error: None,
            })
        }
    }

    export_tool!(MacroTestTool);

    #[test]
    fn test_macro_get_tool_returns_singleton() {
        let tool = get_tool();
        assert_eq!(tool.name(), "macro_test");
        // Verify that two calls return the same &'static reference (singleton identity).
        let tool2 = get_tool();
        assert!(std::ptr::eq(tool, tool2));
    }

    #[test]
    fn test_macro_get_spec_null_pointer_is_safe() {
        // A null pointer should not cause UB — the function should return early.
        unsafe {
            __amplifier_tool_get_spec(std::ptr::null_mut());
        }
    }

    #[test]
    fn test_macro_get_spec_len_positive() {
        let len = __amplifier_tool_get_spec_len();
        assert!(len > 0);
    }

    #[test]
    fn test_macro_get_spec_len_matches_serialized() {
        let len = __amplifier_tool_get_spec_len();
        let spec = get_tool().get_spec();
        let expected_json = serde_json::to_vec(&spec).unwrap();
        assert_eq!(len as usize, expected_json.len());
    }

    #[test]
    fn test_macro_get_spec_roundtrip() {
        let len = __amplifier_tool_get_spec_len() as usize;
        let mut buf = vec![0u8; len];
        // SAFETY: buf is exactly `len` bytes, matching __amplifier_tool_get_spec_len().
        unsafe { __amplifier_tool_get_spec(buf.as_mut_ptr()) };

        let spec: ToolSpec = serde_json::from_slice(&buf).unwrap();
        assert_eq!(spec.name, "macro_test");
        assert!(spec.parameters.contains_key("x"));
        assert_eq!(
            spec.description,
            Some("A test tool for macro validation".to_string())
        );
    }
}

// ===========================================================================
// HookHandler trait tests
// ===========================================================================

#[cfg(test)]
mod hook_handler_tests {
    use super::*;
    use serde_json::json;

    #[derive(Default)]
    struct TestHook;

    impl HookHandler for TestHook {
        fn handle(&self, event: &str, _data: Value) -> Result<HookResult, String> {
            match event {
                "before_tool" => Ok(HookResult {
                    action: HookAction::Continue,
                    reason: Some(format!("allowed: {}", event)),
                    ..HookResult::default()
                }),
                "blocked" => Err("denied by policy".to_string()),
                _ => Ok(HookResult::default()),
            }
        }
    }

    #[test]
    fn test_hook_handler_handle_success() {
        let hook = TestHook;
        let result = hook.handle("before_tool", json!({"tool": "echo"}));
        assert!(result.is_ok());
        let hr = result.unwrap();
        assert_eq!(hr.action, HookAction::Continue);
        assert_eq!(hr.reason, Some("allowed: before_tool".to_string()));
    }

    #[test]
    fn test_hook_handler_handle_error() {
        let hook = TestHook;
        let result = hook.handle("blocked", json!({}));
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), "denied by policy");
    }

    #[test]
    fn test_hook_handler_handle_default_event() {
        let hook = TestHook;
        let result = hook.handle("unknown_event", json!(null));
        assert!(result.is_ok());
        let hr = result.unwrap();
        assert_eq!(hr.action, HookAction::Continue);
    }
}

#[cfg(test)]
mod hook_macro_tests {
    use super::*;
    use serde_json::json;

    #[derive(Default)]
    struct MacroTestHook;

    impl HookHandler for MacroTestHook {
        fn handle(&self, _event: &str, _data: Value) -> Result<HookResult, String> {
            Ok(HookResult::default())
        }
    }

    export_hook!(MacroTestHook);

    #[test]
    fn test_export_hook_returns_singleton() {
        let hook = get_hook();
        let hook2 = get_hook();
        assert!(std::ptr::eq(hook, hook2));
    }

    #[test]
    fn test_export_hook_handle_delegates() {
        let hook = get_hook();
        let result = hook.handle("test_event", json!({"key": "value"}));
        assert!(result.is_ok());
        let hr = result.unwrap();
        assert_eq!(hr.action, HookAction::Continue);
    }
}

// ===========================================================================
// ContextManager trait tests
// ===========================================================================

#[cfg(test)]
mod context_manager_tests {
    use super::*;
    use serde_json::json;

    #[derive(Default)]
    struct TestContext {
        // Use a RefCell to allow interior mutability for testing.
        messages: std::cell::RefCell<Vec<Value>>,
    }

    impl ContextManager for TestContext {
        fn add_message(&self, message: Value) -> Result<(), String> {
            self.messages.borrow_mut().push(message);
            Ok(())
        }

        fn get_messages(&self) -> Result<Vec<Value>, String> {
            Ok(self.messages.borrow().clone())
        }

        fn get_messages_for_request(&self, _request: Value) -> Result<Vec<Value>, String> {
            // Return all messages for any request in this simple test impl.
            Ok(self.messages.borrow().clone())
        }

        fn set_messages(&self, messages: Vec<Value>) -> Result<(), String> {
            *self.messages.borrow_mut() = messages;
            Ok(())
        }

        fn clear(&self) -> Result<(), String> {
            self.messages.borrow_mut().clear();
            Ok(())
        }
    }

    #[test]
    fn test_context_manager_add_message() {
        let ctx = TestContext::default();
        let result = ctx.add_message(json!({"role": "user", "content": "hello"}));
        assert!(result.is_ok());
        assert_eq!(ctx.messages.borrow().len(), 1);
    }

    #[test]
    fn test_context_manager_get_messages_empty() {
        let ctx = TestContext::default();
        let msgs = ctx.get_messages().unwrap();
        assert!(msgs.is_empty());
    }

    #[test]
    fn test_context_manager_get_messages_after_add() {
        let ctx = TestContext::default();
        ctx.add_message(json!({"role": "user", "content": "hi"})).unwrap();
        ctx.add_message(json!({"role": "assistant", "content": "hey"})).unwrap();
        let msgs = ctx.get_messages().unwrap();
        assert_eq!(msgs.len(), 2);
        assert_eq!(msgs[0]["role"], "user");
        assert_eq!(msgs[1]["role"], "assistant");
    }

    #[test]
    fn test_context_manager_get_messages_for_request() {
        let ctx = TestContext::default();
        ctx.add_message(json!({"role": "user", "content": "test"})).unwrap();
        let msgs = ctx.get_messages_for_request(json!({"model": "gpt-4"})).unwrap();
        assert_eq!(msgs.len(), 1);
    }

    #[test]
    fn test_context_manager_set_messages() {
        let ctx = TestContext::default();
        ctx.add_message(json!("old")).unwrap();
        let new_msgs = vec![json!("a"), json!("b")];
        ctx.set_messages(new_msgs).unwrap();
        let msgs = ctx.get_messages().unwrap();
        assert_eq!(msgs.len(), 2);
        assert_eq!(msgs[0], json!("a"));
        assert_eq!(msgs[1], json!("b"));
    }

    #[test]
    fn test_context_manager_clear() {
        let ctx = TestContext::default();
        ctx.add_message(json!("msg1")).unwrap();
        ctx.add_message(json!("msg2")).unwrap();
        ctx.clear().unwrap();
        let msgs = ctx.get_messages().unwrap();
        assert!(msgs.is_empty());
    }

    // A ContextManager implementation that returns errors, exercising the Err path.
    #[derive(Default)]
    struct FailingContext;

    impl ContextManager for FailingContext {
        fn add_message(&self, _message: Value) -> Result<(), String> {
            Err("context full".to_string())
        }
        fn get_messages(&self) -> Result<Vec<Value>, String> {
            Err("storage unavailable".to_string())
        }
        fn get_messages_for_request(&self, _request: Value) -> Result<Vec<Value>, String> {
            Err("invalid request".to_string())
        }
        fn set_messages(&self, _messages: Vec<Value>) -> Result<(), String> {
            Err("read-only context".to_string())
        }
        fn clear(&self) -> Result<(), String> {
            Err("clear not permitted".to_string())
        }
    }

    #[test]
    fn test_context_manager_add_message_error() {
        let ctx = FailingContext;
        let result = ctx.add_message(json!({"role": "user"}));
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), "context full");
    }

    #[test]
    fn test_context_manager_get_messages_error() {
        let ctx = FailingContext;
        let result = ctx.get_messages();
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), "storage unavailable");
    }

    #[test]
    fn test_context_manager_get_messages_for_request_error() {
        let ctx = FailingContext;
        let result = ctx.get_messages_for_request(json!({"model": "gpt-4"}));
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), "invalid request");
    }

    #[test]
    fn test_context_manager_set_messages_error() {
        let ctx = FailingContext;
        let result = ctx.set_messages(vec![json!("msg")]);
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), "read-only context");
    }

    #[test]
    fn test_context_manager_clear_error() {
        let ctx = FailingContext;
        let result = ctx.clear();
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), "clear not permitted");
    }
}

#[cfg(test)]
mod context_macro_tests {
    use super::*;
    use serde_json::json;

    #[derive(Default)]
    struct MacroTestContext;

    impl ContextManager for MacroTestContext {
        fn add_message(&self, _message: Value) -> Result<(), String> {
            Ok(())
        }
        fn get_messages(&self) -> Result<Vec<Value>, String> {
            Ok(vec![json!({"role": "system", "content": "default"})])
        }
        fn get_messages_for_request(&self, _request: Value) -> Result<Vec<Value>, String> {
            Ok(vec![])
        }
        fn set_messages(&self, _messages: Vec<Value>) -> Result<(), String> {
            Ok(())
        }
        fn clear(&self) -> Result<(), String> {
            Ok(())
        }
    }

    export_context!(MacroTestContext);

    #[test]
    fn test_export_context_returns_singleton() {
        let ctx = get_context();
        let ctx2 = get_context();
        assert!(std::ptr::eq(ctx, ctx2));
    }

    #[test]
    fn test_export_context_delegates_get_messages() {
        let ctx = get_context();
        let msgs = ctx.get_messages().unwrap();
        assert_eq!(msgs.len(), 1);
        assert_eq!(msgs[0]["role"], "system");
    }
}

// ===========================================================================
// ApprovalProvider trait tests
// ===========================================================================

#[cfg(test)]
mod approval_provider_tests {
    use super::*;
    use serde_json::json;
    use std::collections::HashMap;

    #[derive(Default)]
    struct TestApproval;

    impl ApprovalProvider for TestApproval {
        fn request_approval(&self, request: ApprovalRequest) -> Result<ApprovalResponse, String> {
            if request.risk_level == "critical" {
                Ok(ApprovalResponse {
                    approved: false,
                    reason: Some("auto-denied: critical risk".to_string()),
                    remember: false,
                })
            } else {
                Ok(ApprovalResponse {
                    approved: true,
                    reason: None,
                    remember: true,
                })
            }
        }
    }

    #[test]
    fn test_approval_provider_approve() {
        let provider = TestApproval;
        let req = ApprovalRequest {
            tool_name: "ls".to_string(),
            action: "list".to_string(),
            details: HashMap::new(),
            risk_level: "low".to_string(),
            timeout: None,
        };
        let result = provider.request_approval(req);
        assert!(result.is_ok());
        let resp = result.unwrap();
        assert!(resp.approved);
        assert!(resp.remember);
        assert!(resp.reason.is_none());
    }

    #[test]
    fn test_approval_provider_deny() {
        let provider = TestApproval;
        let req = ApprovalRequest {
            tool_name: "rm".to_string(),
            action: "delete".to_string(),
            details: {
                let mut m = HashMap::new();
                m.insert("path".to_string(), json!("/"));
                m
            },
            risk_level: "critical".to_string(),
            timeout: Some(30.0),
        };
        let result = provider.request_approval(req);
        assert!(result.is_ok());
        let resp = result.unwrap();
        assert!(!resp.approved);
        assert_eq!(resp.reason, Some("auto-denied: critical risk".to_string()));
        assert!(!resp.remember);
    }
}

#[cfg(test)]
mod approval_macro_tests {
    use super::*;
    use std::collections::HashMap;

    #[derive(Default)]
    struct MacroTestApproval;

    impl ApprovalProvider for MacroTestApproval {
        fn request_approval(&self, _request: ApprovalRequest) -> Result<ApprovalResponse, String> {
            Ok(ApprovalResponse {
                approved: true,
                reason: None,
                remember: false,
            })
        }
    }

    export_approval!(MacroTestApproval);

    #[test]
    fn test_export_approval_returns_singleton() {
        let ap = get_approval();
        let ap2 = get_approval();
        assert!(std::ptr::eq(ap, ap2));
    }

    #[test]
    fn test_export_approval_delegates_request() {
        let ap = get_approval();
        let req = ApprovalRequest {
            tool_name: "test".to_string(),
            action: "run".to_string(),
            details: HashMap::new(),
            risk_level: "low".to_string(),
            timeout: None,
        };
        let result = ap.request_approval(req);
        assert!(result.is_ok());
        assert!(result.unwrap().approved);
    }
}

// ===========================================================================
// Provider trait tests
// ===========================================================================

#[cfg(test)]
mod provider_tests {
    use super::*;
    use serde_json::json;
    use std::collections::HashMap;

    #[derive(Default)]
    struct TestProvider;

    impl Provider for TestProvider {
        fn name(&self) -> &str {
            "test-provider"
        }

        fn get_info(&self) -> ProviderInfo {
            ProviderInfo {
                id: "test".to_string(),
                display_name: "Test Provider".to_string(),
                credential_env_vars: vec!["TEST_API_KEY".to_string()],
                capabilities: vec!["chat".to_string()],
                defaults: HashMap::new(),
            }
        }

        fn list_models(&self) -> Result<Vec<ModelInfo>, String> {
            Ok(vec![ModelInfo {
                id: "test-model".to_string(),
                display_name: "Test Model".to_string(),
                context_window: 4096,
                max_output_tokens: 1024,
                capabilities: vec!["chat".to_string()],
                defaults: HashMap::new(),
            }])
        }

        fn complete(&self, _request: Value) -> Result<ChatResponse, String> {
            Ok(ChatResponse {
                content: vec![json!({"type": "text", "text": "hello"})],
                tool_calls: None,
                finish_reason: Some("stop".to_string()),
                extra: HashMap::new(),
            })
        }

        fn parse_tool_calls(&self, response: &ChatResponse) -> Vec<Value> {
            response.tool_calls.clone().unwrap_or_default()
        }
    }

    #[test]
    fn test_provider_name() {
        let p = TestProvider;
        assert_eq!(p.name(), "test-provider");
    }

    #[test]
    fn test_provider_get_info() {
        let p = TestProvider;
        let info = p.get_info();
        assert_eq!(info.id, "test");
        assert_eq!(info.display_name, "Test Provider");
        assert_eq!(info.credential_env_vars, vec!["TEST_API_KEY"]);
    }

    #[test]
    fn test_provider_list_models() {
        let p = TestProvider;
        let models = p.list_models().unwrap();
        assert_eq!(models.len(), 1);
        assert_eq!(models[0].id, "test-model");
        assert_eq!(models[0].context_window, 4096);
    }

    #[test]
    fn test_provider_complete() {
        let p = TestProvider;
        let result = p.complete(json!({"messages": []})).unwrap();
        assert_eq!(result.content.len(), 1);
        assert_eq!(result.finish_reason, Some("stop".to_string()));
    }

    #[test]
    fn test_provider_parse_tool_calls_empty() {
        let p = TestProvider;
        let resp = ChatResponse {
            content: vec![],
            tool_calls: None,
            finish_reason: None,
            extra: HashMap::new(),
        };
        let calls = p.parse_tool_calls(&resp);
        assert!(calls.is_empty());
    }

    #[test]
    fn test_provider_parse_tool_calls_present() {
        let p = TestProvider;
        let resp = ChatResponse {
            content: vec![],
            tool_calls: Some(vec![json!({"name": "echo", "args": {}})]),
            finish_reason: None,
            extra: HashMap::new(),
        };
        let calls = p.parse_tool_calls(&resp);
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0]["name"], "echo");
    }

    #[test]
    fn test_provider_complete_error() {
        #[derive(Default)]
        struct FailProvider;

        impl Provider for FailProvider {
            fn name(&self) -> &str {
                "fail"
            }
            fn get_info(&self) -> ProviderInfo {
                ProviderInfo {
                    id: "fail".to_string(),
                    display_name: "Fail".to_string(),
                    credential_env_vars: vec![],
                    capabilities: vec![],
                    defaults: HashMap::new(),
                }
            }
            fn list_models(&self) -> Result<Vec<ModelInfo>, String> {
                Err("not available".to_string())
            }
            fn complete(&self, _request: Value) -> Result<ChatResponse, String> {
                Err("completion failed".to_string())
            }
            fn parse_tool_calls(&self, _response: &ChatResponse) -> Vec<Value> {
                vec![]
            }
        }

        let p = FailProvider;
        assert!(p.list_models().is_err());
        assert_eq!(p.list_models().unwrap_err(), "not available");
        assert!(p.complete(json!({})).is_err());
        assert_eq!(p.complete(json!({})).unwrap_err(), "completion failed");
    }
}

#[cfg(test)]
mod provider_macro_tests {
    use super::*;
    use std::collections::HashMap;

    #[derive(Default)]
    struct MacroTestProvider;

    impl Provider for MacroTestProvider {
        fn name(&self) -> &str {
            "macro-provider"
        }
        fn get_info(&self) -> ProviderInfo {
            ProviderInfo {
                id: "macro".to_string(),
                display_name: "Macro Provider".to_string(),
                credential_env_vars: vec![],
                capabilities: vec![],
                defaults: HashMap::new(),
            }
        }
        fn list_models(&self) -> Result<Vec<ModelInfo>, String> {
            Ok(vec![])
        }
        fn complete(&self, _request: Value) -> Result<ChatResponse, String> {
            Ok(ChatResponse {
                content: vec![],
                tool_calls: None,
                finish_reason: None,
                extra: HashMap::new(),
            })
        }
        fn parse_tool_calls(&self, _response: &ChatResponse) -> Vec<Value> {
            vec![]
        }
    }

    export_provider!(MacroTestProvider);

    #[test]
    fn test_export_provider_returns_singleton() {
        let p = get_provider();
        let p2 = get_provider();
        assert!(std::ptr::eq(p, p2));
    }

    #[test]
    fn test_export_provider_delegates_name() {
        let p = get_provider();
        assert_eq!(p.name(), "macro-provider");
    }
}

// ===========================================================================
// Orchestrator trait tests
// ===========================================================================

#[cfg(test)]
mod orchestrator_tests {
    use super::*;

    #[derive(Default)]
    struct TestOrchestrator;

    impl Orchestrator for TestOrchestrator {
        fn execute(&self, prompt: String) -> Result<String, String> {
            Ok(format!("executed: {}", prompt))
        }
    }

    #[test]
    fn test_orchestrator_execute_success() {
        let o = TestOrchestrator;
        let result = o.execute("hello".to_string());
        assert!(result.is_ok());
        assert_eq!(result.unwrap(), "executed: hello");
    }

    #[test]
    fn test_orchestrator_execute_error() {
        #[derive(Default)]
        struct FailOrchestrator;

        impl Orchestrator for FailOrchestrator {
            fn execute(&self, _prompt: String) -> Result<String, String> {
                Err("orchestration failed".to_string())
            }
        }

        let o = FailOrchestrator;
        let result = o.execute("test".to_string());
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), "orchestration failed");
    }
}

#[cfg(test)]
mod orchestrator_macro_tests {
    use super::*;

    #[derive(Default)]
    struct MacroTestOrchestrator;

    impl Orchestrator for MacroTestOrchestrator {
        fn execute(&self, prompt: String) -> Result<String, String> {
            Ok(format!("macro: {}", prompt))
        }
    }

    export_orchestrator!(MacroTestOrchestrator);

    #[test]
    fn test_export_orchestrator_returns_singleton() {
        let o = get_orchestrator();
        let o2 = get_orchestrator();
        assert!(std::ptr::eq(o, o2));
    }

    #[test]
    fn test_export_orchestrator_delegates_execute() {
        let o = get_orchestrator();
        let result = o.execute("test".to_string()).unwrap();
        assert_eq!(result, "macro: test");
    }
}

// ===========================================================================
// kernel module tests
// ===========================================================================

#[cfg(test)]
mod kernel_tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_kernel_execute_tool_returns_placeholder_err() {
        let result = kernel::execute_tool("echo", &json!({"msg": "hi"}));
        assert!(result.is_err());
        // Must contain a meaningful placeholder message
        let err = result.unwrap_err();
        assert!(!err.is_empty());
    }

    #[test]
    fn test_kernel_complete_with_provider_returns_placeholder_err() {
        let result = kernel::complete_with_provider("openai", &json!({"messages": []}));
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(!err.is_empty());
    }

    #[test]
    fn test_kernel_emit_hook_returns_placeholder_err() {
        let result = kernel::emit_hook("before_tool", &json!({}));
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(!err.is_empty());
    }

    #[test]
    fn test_kernel_get_messages_returns_placeholder_err() {
        let result = kernel::get_messages();
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(!err.is_empty());
    }

    #[test]
    fn test_kernel_add_message_returns_placeholder_err() {
        let result = kernel::add_message(&json!({"role": "user", "content": "hello"}));
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(!err.is_empty());
    }

    #[test]
    fn test_kernel_get_capability_returns_placeholder_err() {
        let result = kernel::get_capability("tool_execution");
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(!err.is_empty());
    }

    #[test]
    fn test_kernel_register_capability_returns_placeholder_err() {
        let result = kernel::register_capability("my_cap", &json!({"version": 1}));
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(!err.is_empty());
    }
}

// ===========================================================================
// WASM fixture acceptance tests
// ===========================================================================

#[cfg(test)]
mod wasm_fixture_tests {
    use std::path::Path;

    #[test]
    fn test_deny_hook_wasm_fixture_exists_and_has_valid_size() {
        // The deny-hook.wasm fixture must exist and be > 1000 bytes.
        let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/wasm/deny-hook.wasm");
        assert!(
            fixture_path.exists(),
            "deny-hook.wasm fixture not found at {:?}",
            fixture_path
        );
        let metadata = std::fs::metadata(&fixture_path).expect("failed to read file metadata");
        assert!(
            metadata.len() > 1000,
            "deny-hook.wasm is too small: {} bytes (expected > 1000)",
            metadata.len()
        );
    }

    #[test]
    fn test_deny_hook_wasm_fixture_has_wasm_magic_bytes() {
        // Verify the file starts with the WASM magic number (\0asm).
        let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/wasm/deny-hook.wasm");
        let bytes = std::fs::read(&fixture_path).expect("failed to read wasm file");
        assert!(
            bytes.len() >= 4,
            "deny-hook.wasm too small to contain magic bytes"
        );
        assert_eq!(
            &bytes[0..4],
            b"\0asm",
            "deny-hook.wasm does not start with WASM magic bytes"
        );
    }

    #[test]
    fn test_memory_context_wasm_fixture_exists_and_has_valid_size() {
        // The memory-context.wasm fixture must exist and be > 1000 bytes.
        let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/wasm/memory-context.wasm");
        assert!(
            fixture_path.exists(),
            "memory-context.wasm fixture not found at {:?}",
            fixture_path
        );
        let metadata = std::fs::metadata(&fixture_path).expect("failed to read file metadata");
        assert!(
            metadata.len() > 1000,
            "memory-context.wasm is too small: {} bytes (expected > 1000)",
            metadata.len()
        );
    }

    #[test]
    fn test_memory_context_wasm_fixture_has_wasm_magic_bytes() {
        // Verify the file starts with the WASM magic number (\0asm).
        let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/wasm/memory-context.wasm");
        let bytes = std::fs::read(&fixture_path).expect("failed to read wasm file");
        assert!(
            bytes.len() >= 4,
            "memory-context.wasm too small to contain magic bytes"
        );
        assert_eq!(
            &bytes[0..4],
            b"\0asm",
            "memory-context.wasm does not start with WASM magic bytes"
        );
    }

    #[test]
    fn test_auto_approve_wasm_fixture_exists_and_has_valid_size() {
        // The auto-approve.wasm fixture must exist and be > 1000 bytes.
        let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/wasm/auto-approve.wasm");
        assert!(
            fixture_path.exists(),
            "auto-approve.wasm fixture not found at {:?}",
            fixture_path
        );
        let metadata = std::fs::metadata(&fixture_path).expect("failed to read file metadata");
        assert!(
            metadata.len() > 1000,
            "auto-approve.wasm is too small: {} bytes (expected > 1000)",
            metadata.len()
        );
    }

    #[test]
    fn test_auto_approve_wasm_fixture_has_wasm_magic_bytes() {
        // Verify the file starts with the WASM magic number (\0asm).
        let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/wasm/auto-approve.wasm");
        let bytes = std::fs::read(&fixture_path).expect("failed to read wasm file");
        assert!(
            bytes.len() >= 4,
            "auto-approve.wasm too small to contain magic bytes"
        );
        assert_eq!(
            &bytes[0..4],
            b"\0asm",
            "auto-approve.wasm does not start with WASM magic bytes"
        );
    }

    #[test]
    fn test_echo_provider_wasm_fixture_exists_and_has_valid_size() {
        // The echo-provider.wasm fixture must exist and be > 1000 bytes.
        let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/wasm/echo-provider.wasm");
        assert!(
            fixture_path.exists(),
            "echo-provider.wasm fixture not found at {:?}",
            fixture_path
        );
        let metadata = std::fs::metadata(&fixture_path).expect("failed to read file metadata");
        assert!(
            metadata.len() > 1000,
            "echo-provider.wasm is too small: {} bytes (expected > 1000)",
            metadata.len()
        );
    }

    #[test]
    fn test_echo_provider_wasm_fixture_has_wasm_magic_bytes() {
        // Verify the file starts with the WASM magic number (\0asm).
        let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/wasm/echo-provider.wasm");
        let bytes = std::fs::read(&fixture_path).expect("failed to read wasm file");
        assert!(
            bytes.len() >= 4,
            "echo-provider.wasm too small to contain magic bytes"
        );
        assert_eq!(
            &bytes[0..4],
            b"\0asm",
            "echo-provider.wasm does not start with WASM magic bytes"
        );
    }
}
