/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hello(): string
export const enum HookAction {
  Continue = 'Continue',
  Deny = 'Deny',
  Modify = 'Modify',
  InjectContext = 'InjectContext',
  AskUser = 'AskUser'
}
export const enum SessionState {
  Running = 'Running',
  Completed = 'Completed',
  Failed = 'Failed',
  Cancelled = 'Cancelled'
}
export const enum ContextInjectionRole {
  System = 'System',
  User = 'User',
  Assistant = 'Assistant'
}
export const enum ApprovalDefault {
  Allow = 'Allow',
  Deny = 'Deny'
}
export const enum UserMessageLevel {
  Info = 'Info',
  Warning = 'Warning',
  Error = 'Error'
}
export interface JsHookResult {
  action: HookAction
  reason?: string
  contextInjection?: string
  contextInjectionRole?: ContextInjectionRole
  ephemeral?: boolean
  suppressOutput?: boolean
  userMessage?: string
  userMessageLevel?: UserMessageLevel
  userMessageSource?: string
  approvalPrompt?: string
  approvalTimeout?: number
  approvalDefault?: ApprovalDefault
}
/** Structured error object returned to JS with a typed `code` property. */
export interface JsAmplifierError {
  code: string
  message: string
}
/**
 * Converts an error variant name and message into a typed `JsAmplifierError`.
 *
 * See [`error_code_for_variant`] for the variant → code mapping.
 */
export declare function amplifierErrorToJs(variant: string, message: string): JsAmplifierError
/** Result from resolving a module path. */
export interface JsModuleManifest {
  /**
   * How the module is loaded and invoked.
   *
   * Valid values (string literal union):
   * `"python"` | `"wasm"` | `"grpc"` | `"native"`
   */
  transport: string
  /**
   * Logical role the module plays inside the kernel.
   *
   * Valid values (string literal union):
   * `"tool"` | `"hook"` | `"context"` | `"approval"` | `"provider"` | `"orchestrator"`
   */
  moduleType: string
  /**
   * Artifact format used to locate or load the module.
   *
   * Valid values (string literal union):
   * `"wasm"` | `"grpc"` | `"python"`
   *
   * - `"wasm"` — `artifactPath` contains the `.wasm` component file path
   * - `"grpc"` — `endpoint` contains the gRPC service URL
   * - `"python"` — `packageName` contains the importable Python package name
   */
  artifactType: string
  /** Path to WASM artifact (present when `artifactType` is `"wasm"`). */
  artifactPath?: string
  /** gRPC service endpoint URL (present when `artifactType` is `"grpc"`). */
  endpoint?: string
  /** Python package name for import (present when `artifactType` is `"python"`). */
  packageName?: string
}
/**
 * Resolve a module from a filesystem path.
 *
 * Returns a JsModuleManifest describing the transport, module type, and artifact.
 */
export declare function resolveModule(path: string): JsModuleManifest
/**
 * Load a WASM module from a path and return status info.
 *
 * For WASM modules: loads the component and returns module type info.
 * For Python modules: returns an error (TS host can't load Python).
 */
export declare function loadWasmFromPath(path: string): string
/**
 * Wraps `amplifier_core::CancellationToken` for Node.js.
 *
 * State machine: None → Graceful → Immediate, with reset back to None.
 */
export declare class JsCancellationToken {
  constructor()
  get isCancelled(): boolean
  get isGraceful(): boolean
  get isImmediate(): boolean
  requestGraceful(): void
  requestImmediate(): void
  reset(): void
}
/**
 * Wraps `amplifier_core::HookRegistry` for Node.js.
 *
 * Provides register/emit/listHandlers/setDefaultFields — the event backbone
 * of the kernel.
 */
export declare class JsHookRegistry {
  constructor()
  /**
   * Register a hook handler for the given event name.
   *
   * ## Handler signature
   *
   * The `handler` callback receives two string arguments and must return a
   * JSON-serialized `HookResult` (or a `Promise` that resolves to one):
   *
   * ```ts
   * (event: string, dataJson: string) => string | Promise<string>
   * ```
   *
   * Where the return value is a JSON string matching the `JsHookResult`
   * shape, e.g. `'{"action":"Continue"}'`.  If the handler returns an
   * invalid JSON string, the kernel fails closed and treats it as `Deny`.
   */
  register(event: string, handler: (...args: any[]) => any, priority: number, name: string): void
  emit(event: string, dataJson: string): Promise<JsHookResult>
  listHandlers(): Record<string, Array<string>>
  setDefaultFields(defaultsJson: string): void
}
/**
 * Wraps `amplifier_core::Coordinator` for Node.js — the central hub holding
 * module mount points, capabilities, hook registry, cancellation token, and config.
 *
 * Implements the hybrid coordinator pattern: JS-side storage for TS module
 * objects, Rust kernel for everything else.
 */
export declare class JsCoordinator {
  constructor(configJson: string)
  get toolNames(): Array<string>
  get providerNames(): Array<string>
  get hasOrchestrator(): boolean
  get hasContext(): boolean
  registerCapability(name: string, valueJson: string): void
  getCapability(name: string): string | null
  /**
   * Creates a new **detached** (empty) JsHookRegistry.
   *
   * ⚠吅  **Each call returns a brand-new, empty registry** — hooks registered
   * on one instance are invisible to the next. This is a known limitation:
   * `Coordinator` owns its `HookRegistry` by value, not behind `Arc`, so
   * the binding cannot share state across calls.
   *
   * The method name (`createHookRegistry`) intentionally signals "creates new
   * instance" — a getter property would imply referential stability in JS.
   *
   * **Workaround:** create a `JsHookRegistry` directly and hold a reference.
   *
   * Future TODO #1: restructure the kernel to hold `Arc<HookRegistry>` inside
   * `Coordinator` so this method can share the same registry instance.
   */
  createHookRegistry(): JsHookRegistry
  get cancellation(): JsCancellationToken
  get config(): string
  resetTurn(): void
  toDict(): Record<string, any>
  cleanup(): Promise<void>
}
/**
 * Wraps `amplifier_core::Session` for Node.js — the top-level entry point.
 *
 * Lifecycle: `new AmplifierSession(config) → initialize() → execute(prompt) → cleanup()`.
 * Wires together Coordinator, HookRegistry, and CancellationToken.
 *
 * Known limitation: `coordinator` getter creates a separate Coordinator instance
 * because the kernel Session owns its Coordinator by value, not behind Arc.
 * Sharing requires restructuring the Rust kernel — tracked as Future TODO #1.
 */
export declare class JsAmplifierSession {
  constructor(configJson: string, sessionId?: string | undefined | null, parentId?: string | undefined | null)
  get sessionId(): string
  get parentId(): string | null
  get isInitialized(): boolean
  /**
   * Current session lifecycle state as a lowercase string.
   *
   * Returns one of the `SessionState` variant strings:
   * - `"Running"` — session is active
   * - `"Completed"` — session finished successfully
   * - `"Failed"` — session encountered a fatal error
   * - `"Cancelled"` — session was cancelled via the cancellation token
   *
   * Falls back to `"running"` if the session lock is held during `cleanup()`.
   */
  get status(): string
  /**
   * Creates a new **fresh** JsCoordinator from this session's cached config.
   *
   * ⚠吅  **Each call allocates a new Coordinator** — capabilities registered on
   * one instance are invisible to the next. This is a known limitation:
   * `Session` owns its `Coordinator` by value, not behind `Arc`, so the
   * binding cannot expose the session's live coordinator.
   *
   * The method name (`createCoordinator`) intentionally signals "creates new
   * instance" — a getter property would imply referential stability in JS.
   *
   * **Workaround:** call `createCoordinator()` once, hold the returned instance,
   * and register capabilities on it before passing it to other APIs.
   *
   * Future TODO #1: restructure the kernel to hold `Arc<Coordinator>` inside
   * `Session` so this method can return a handle to the session's actual coordinator.
   */
  createCoordinator(): JsCoordinator
  setInitialized(): void
  cleanup(): Promise<void>
}
/**
 * Bridges a TypeScript tool object to Rust via `ThreadsafeFunction`.
 *
 * In the hybrid coordinator pattern, these bridge objects are stored in a
 * JS-side Map (not in the Rust Coordinator). The JS orchestrator retrieves
 * them by name and calls `execute()` directly.
 */
export declare class JsToolBridge {
  constructor(name: string, description: string, parametersJson: string, executeFn: (inputJson: string) => Promise<string>)
  get name(): string
  get description(): string
  execute(inputJson: string): Promise<string>
  getSpec(): string
}
