/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hello(): string
export const enum HookAction {
  Continue = 'Continue',
  Deny = 'Deny',
  Modify = 'Modify',
  InjectContext = 'InjectContext',
  AskUser = 'AskUser'
}
export const enum SessionState {
  Running = 'Running',
  Completed = 'Completed',
  Failed = 'Failed',
  Cancelled = 'Cancelled'
}
export const enum ContextInjectionRole {
  System = 'System',
  User = 'User',
  Assistant = 'Assistant'
}
export const enum ApprovalDefault {
  Allow = 'Allow',
  Deny = 'Deny'
}
export const enum UserMessageLevel {
  Info = 'Info',
  Warning = 'Warning',
  Error = 'Error'
}
export const enum Role {
  System = 'System',
  Developer = 'Developer',
  User = 'User',
  Assistant = 'Assistant',
  Function = 'Function',
  Tool = 'Tool'
}
export interface JsToolResult {
  success: boolean
  output?: string
  error?: string
}
export interface JsToolSpec {
  name: string
  description?: string
  parametersJson: string
}
export interface JsHookResult {
  action: HookAction
  reason?: string
  contextInjection?: string
  contextInjectionRole?: ContextInjectionRole
  ephemeral?: boolean
  suppressOutput?: boolean
  userMessage?: string
  userMessageLevel?: UserMessageLevel
  userMessageSource?: string
  approvalPrompt?: string
  approvalTimeout?: number
  approvalDefault?: ApprovalDefault
}
export interface JsSessionConfig {
  configJson: string
}
/** Structured error object returned to JS with a typed `code` property. */
export interface JsAmplifierError {
  code: string
  message: string
}
/**
 * Converts an error variant name and message into a typed `JsAmplifierError`.
 *
 * See [`error_code_for_variant`] for the variant → code mapping.
 */
export declare function amplifierErrorToJs(variant: string, message: string): JsAmplifierError
/** Result from resolving a module path. */
export interface JsModuleManifest {
  /** Transport type: "python", "wasm", "grpc", "native" */
  transport: string
  /** Module type: "tool", "hook", "context", "approval", "provider", "orchestrator" */
  moduleType: string
  /** Artifact type: "wasm", "grpc", "python" */
  artifactType: string
  /** Path to WASM artifact (if artifact_type is "wasm") */
  artifactPath?: string
  /** gRPC endpoint (if artifact_type is "grpc") */
  endpoint?: string
  /** Python package name (if artifact_type is "python") */
  packageName?: string
}
/**
 * Resolve a module from a filesystem path.
 *
 * Returns a JsModuleManifest describing the transport, module type, and artifact.
 */
export declare function resolveModule(path: string): JsModuleManifest
/**
 * Load a WASM module from a path and return status info.
 *
 * For WASM modules: loads the component and returns module type info.
 * For Python modules: returns an error (TS host can't load Python).
 */
export declare function loadWasmFromPath(path: string): string
/**
 * Wraps `amplifier_core::CancellationToken` for Node.js.
 *
 * State machine: None → Graceful → Immediate, with reset back to None.
 */
export declare class JsCancellationToken {
  constructor()
  get isCancelled(): boolean
  get isGraceful(): boolean
  get isImmediate(): boolean
  requestGraceful(reason?: string | undefined | null): void
  requestImmediate(reason?: string | undefined | null): void
  reset(): void
}
/**
 * Wraps `amplifier_core::HookRegistry` for Node.js.
 *
 * Provides register/emit/listHandlers/setDefaultFields — the event backbone
 * of the kernel.
 */
export declare class JsHookRegistry {
  constructor()
  register(event: string, handler: (...args: any[]) => any, priority: number, name: string): void
  emit(event: string, dataJson: string): Promise<JsHookResult>
  listHandlers(): Record<string, Array<string>>
  setDefaultFields(defaultsJson: string): void
}
/**
 * Wraps `amplifier_core::Coordinator` for Node.js — the central hub holding
 * module mount points, capabilities, hook registry, cancellation token, and config.
 *
 * Implements the hybrid coordinator pattern: JS-side storage for TS module
 * objects, Rust kernel for everything else.
 */
export declare class JsCoordinator {
  constructor(configJson: string)
  get toolNames(): Array<string>
  get providerNames(): Array<string>
  get hasOrchestrator(): boolean
  get hasContext(): boolean
  registerCapability(name: string, valueJson: string): void
  getCapability(name: string): string | null
  /**
   * Returns a JsHookRegistry wrapper.
   *
   * TODO: Share hook registry via Arc — currently creates a separate (detached)
   * HookRegistry because Coordinator owns HookRegistry by value, not behind Arc.
   * See JsAmplifierSession known limitation (Future TODO #1).
   */
  get hooks(): JsHookRegistry
  get cancellation(): JsCancellationToken
  get config(): string
  resetTurn(): void
  toDict(): Record<string, any>
  cleanup(): Promise<void>
}
/**
 * Wraps `amplifier_core::Session` for Node.js — the top-level entry point.
 *
 * Lifecycle: `new AmplifierSession(config) → initialize() → execute(prompt) → cleanup()`.
 * Wires together Coordinator, HookRegistry, and CancellationToken.
 *
 * Known limitation: `coordinator` getter creates a separate Coordinator instance
 * because the kernel Session owns its Coordinator by value, not behind Arc.
 * Sharing requires restructuring the Rust kernel — tracked as Future TODO #1.
 */
export declare class JsAmplifierSession {
  constructor(configJson: string, sessionId?: string | undefined | null, parentId?: string | undefined | null)
  get sessionId(): string
  get parentId(): string | null
  get isInitialized(): boolean
  get status(): string
  /**
   * Returns a JsCoordinator wrapper.
   *
   * Known limitation: creates a separate Coordinator instance from cached config
   * because the kernel Session owns its Coordinator by value. Sharing requires
   * restructuring the Rust kernel to use Arc<Coordinator> — Future TODO #1.
   *
   * Note: each call clones `cached_config` and allocates a new Coordinator.
   * Callers should cache the result rather than calling this in a loop.
   */
  get coordinator(): JsCoordinator
  setInitialized(): void
  cleanup(): Promise<void>
}
/**
 * Bridges a TypeScript tool object to Rust via `ThreadsafeFunction`.
 *
 * In the hybrid coordinator pattern, these bridge objects are stored in a
 * JS-side Map (not in the Rust Coordinator). The JS orchestrator retrieves
 * them by name and calls `execute()` directly.
 */
export declare class JsToolBridge {
  constructor(name: string, description: string, parametersJson: string, executeFn: (inputJson: string) => Promise<string>)
  get name(): string
  get description(): string
  execute(inputJson: string): Promise<string>
  getSpec(): string
}
